From python:3.8-slim
RUN pip install fastapi uvicorn
RUN pip install redis pymongo
RUN pip install paramiko requests
WORKDIR /src
COPY ./src /src
CMD ["uvicorn", "api_foundation:app", "--host", "0.0.0.0", "--port", "80", "--reload"]