version: '3.7'

services:

  web:
    build:
      context: ./web
      dockerfile: Dockerfile_local_nginx
    image: web_nginx.labtool.nutanix.jp
    container_name: web_nginx.labtool.nutanix.jp
    environment: &environment
      WEB_PORT: 80
      NODE_HOST: node
      NODE_PORT: 80
      API_AUTH_HOST: api_auth
      API_AUTH_PORT: 80
      API_AUTH_PASSWORD_ENCKEY: "api_auth.labtool.nutanix.jp"
      API_AUTH_DEBUG: "False"
      API_AUTH_DROPDB: "False"
      API_CLUSTER_HOST: api_cluster
      API_CLUSTER_PORT: 80
      API_TASK_HOST: api_task
      API_TASK_PORT: 80 
      API_FOUNDATION_HOST: api_foundation
      API_FOUNDATION_PORT: 80      
      API_EULA_HOST: api_eula
      API_EULA_PORT: 80   
      API_SETUP_HOST: api_setup
      API_SETUP_PORT: 80   
      API_POWER_HOST: api_power
      API_POWER_PORT: 80   
      MONGO_HOST: mongo
      MONGO_PORT: 27017
      MONGO_USERNAME: root
      MONGO_PASSWORD: example
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
    ports:
    - 80:80
    depends_on:
    - node
    - api_auth
    - api_cluster
    - api_task
    - api_foundation
    - api_eula
    - api_setup
    - api_power
    - mongo
    - redis

  node: 
    build:
      context: ./web
      dockerfile: Dockerfile_local_node
    image: web_node.labtool.nutanix.jp
    container_name: web_node.labtool.nutanix.jp
    ports:
      - 8000:80
    environment: *environment
    volumes:
      - ./web/src:/node/src


  api_auth:
    build:
      context: ./api_auth
      dockerfile: Dockerfile
    image: api_auth.labtool.nutanix.jp
    container_name: api_auth.labtool.nutanix.jp
    environment: *environment
    ports:
    - 8090:80
    volumes:
    - ./api_auth/src:/src
    depends_on:
    - mongo
    - redis

  manager_task:
    build:
      context: ./api_ntnx
      dockerfile: Dockerfile.manager_task.yml
    image: manager_task.labtool.nutanix.jp
    container_name: manager_task.labtool.nutanix.jp
    environment: *environment
    volumes:
    - ./api_ntnx/src:/src
    depends_on:
    - mongo
    - redis

  api_task:
    build:
      context: ./api_ntnx
      dockerfile: Dockerfile.api_task.yml
    image: api_task.labtool.nutanix.jp
    container_name: api_task.labtool.nutanix.jp
    ports:
    - 8100:80
    environment: *environment
    volumes:
    - ./api_ntnx/src:/src
    depends_on:
    - mongo
    - redis
    - api_auth

  api_cluster:
    build:
      context: ./api_ntnx
      dockerfile: Dockerfile.api_cluster.yml
    image: api_cluster.labtool.nutanix.jp
    container_name: api_cluster.labtool.nutanix.jp
    ports:
    - 8110:80
    environment: *environment
    volumes:
    - ./api_ntnx/src:/src
    depends_on:
    - mongo
    - redis
    - api_auth

  api_foundation:
    build:
      context: ./api_ntnx
      dockerfile: Dockerfile.api_foundation.yml
    image: api_foundation.labtool.nutanix.jp
    container_name: api_foundation.labtool.nutanix.jp
    ports:
    - 8120:80
    environment: *environment
    volumes:
    - ./api_ntnx/src:/src
    depends_on:
    - mongo
    - redis
    - api_auth
    
  api_eula:
    build:
      context: ./api_ntnx
      dockerfile: Dockerfile.api_eula.yml
    image: api_eula.labtool.nutanix.jp
    container_name: api_eula.labtool.nutanix.jp
    ports:
    - 8130:80
    environment: *environment
    volumes:
    - ./api_ntnx/src:/src
    depends_on:
    - mongo
    - redis
    - api_auth

  api_setup:
    build:
      context: ./api_ntnx
      dockerfile: Dockerfile.api_setup.yml
    image: api_setup.labtool.nutanix.jp
    container_name: api_setup.labtool.nutanix.jp
    ports:
    - 8140:80
    environment: *environment
    volumes:
    - ./api_ntnx/src:/src
    depends_on:
    - mongo
    - redis
    - api_auth

  api_power:
    build:
      context: ./api_ntnx
      dockerfile: Dockerfile.api_power.yml
    image: api_power.labtool.nutanix.jp
    container_name: api_power.labtool.nutanix.jp
    ports:
    - 8150:80
    environment: *environment
    volumes:
    - ./api_ntnx/src:/src
    depends_on:
    - mongo
    - redis
    - api_auth

#############
### mongo ###
#############

  mongo:
    image: mongo:4.2.3
    container_name: mongo.labtool.nutanix.jp
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example
    ports:
      - 27017:27017
    volumes:
      - mongo.volumes.labtool.nutanix.jp:/data/db

  mongo_express:
    image: mongo-express
    container_name: mongo_express.labtool.nutanix.jp
    environment:
      ME_CONFIG_MONGODB_SERVER: mongo
      ME_CONFIG_MONGODB_PORT: 27017
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example
    ports:
      - 8081:8081
    depends_on:
    - mongo  

#############
### redis ###
#############

  redis:
    image: redis:5.0.6-alpine3.10
    container_name: redis.labtool.nutanix.jp
    volumes:
      - redis.volumes.labtool.nutanix.jp:/data
      
############
## volume ##
############

volumes:
  mongo.volumes.labtool.nutanix.jp:
    driver: local
  redis.volumes.labtool.nutanix.jp:
    driver: local