# Generated by Django 2.2.6 on 2019-11-01 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('task', '0002_auto_20191101_0724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='parent_task',
            field=models.UUIDField(default='', null=True),
        ),
    ]
